css-canvas-medical challenge
kvnliang4/rc0522-code-solutions pull request #21
Opened 2022-05-16 08:02 UTC by kvnliang4

![css-canvas-medical](https://user-images.githubusercontent.com/103390498/168546755-4093de03-b988-4fbf-998d-d5d8449a319c.gif)

2022-05-16 16:56 UTC, Zhiwutian requested changes
Looking good Kevin! Just a few updates:
1. Remove the Form tags from the code
2. Adjust the spacing a position of the nav menu to more closely reflect the example
3. Darken the image just a bit to more match the example image. The filter CSS property is good for that
4. Move the text and button in the `ready to learn more` row in to more closely match the example
5. Move the text in the dark gray footer  off the edge of the element as per the example.
6. Move the text in the bottom footer away from the edge of the element as per the example.

2022-05-16 16:56 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +          <form action="get-started-placeholder.index">
you don't need form elements to have buttons, you can remove all of the form tags on this page.

2022-05-17 01:10 UTC, kvnliang4 commented
![css-canvas-medical-updated](https://user-images.githubusercontent.com/103390498/168707010-b9bfd8ed-0755-488e-9fe3-a328d2d65e14.gif)

2022-05-17 02:40 UTC, Zhiwutian approved these changes
👍🏼

2022-05-20 20:19 UTC, merged